export const LOCAL_ICONS = {
  'logo-instagram': require('../../assets/images/icons/logo-instagram.png'),
  'logo-telegram': require('../../assets/images/icons/logo-telegram.png'),
  'logo-snapchat': require('../../assets/images/icons/logo-snapchat.png'),
  'logo-x': require('../../assets/images/icons/logo-x.png'),
  'logo-twitter': require('../../assets/images/icons/logo-x.png'),
  x: require('../../assets/images/icons/logo-x.png'),
  twitter: require('../../assets/images/icons/logo-x.png'),
  'logo-whatsapp': require('../../assets/images/icons/logo-whatsapp.png'),
  whatsapp: require('../../assets/images/icons/logo-whatsapp.png'),
  'logo-discord': require('../../assets/images/icons/logo-discord.png'),
  discord: require('../../assets/images/icons/logo-discord.png'),
  snapchat: require('../../assets/images/icons/logo-snapchat.png'),
  telegram: require('../../assets/images/icons/logo-telegram.png'),
  'paper-plane': require('../../assets/images/icons/logo-telegram.png'),
  canvas: require('../../assets/images/icons/canvas.png'),
  timeedit: require('../../assets/images/icons/timeedit.png'),
  'e-studentservice': require('../../assets/images/icons/e-studentservice.png'),
  kdg: require('../../assets/images/icons/kdg.png'),
  'kdg-icon': require('../../assets/images/icons/kdg-icon.png'),
  tm: require('../../assets/images/icons/tm.png'),
};
